[package]
name = "image-fingerprint"
version = "0.1.0"
authors = ["Dominic Simone <dominic.simone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
eframe = "0.12.0"
clipboard-win = "2.2.0"
serde = "1.0.117"
serde_json = "1.0.59"